### ISSUE TITLE
Redis 연동

### ISSUE THREAD

**Issue by freddieyyh** [itslaves/rentalgames-server#4]
Redis연동 정보 설정파일 분리
common library로 관리

#2

**Comment by skyoo2003** [comment]
Redis HA 구성 방법 요약

- 1안) 센티넬: Sentinel * 2N+1 <-> (Redis:Master <-> Redis:Slave * M) // 2N+1: 센티넬 노드 수, M: 레디스 슬레이브 노드 수
- 2안) 클러스터: Redis:Master <-> (Redis:Slave * N) % S // N: 슬레이브 노드 수, S: 샤딩 개수

**Comment by skyoo2003** [comment]
### To-do List

- [x] Redis 환경 설정 추가 : 개발 환경은 standalone / 테스트|스테이징|서비스는 HA 방식 구분
- [x] 설정 파일 읽었다고 가정하고, 타입 별로 클라이언트 생성하고 UniversalClient 인터페이스로 관리하는 commons 추가

**Comment by skyoo2003** [comment]
Init / Close 는 메인 함수에서 처리

**Comment by skyoo2003** [comment]
https://github.com/itslaves/rentalgames-server/pull/14 PR 로 처리가 완료되어 이슈 종료
